//
//  ParagramConfigModel.h
//  chechengwang
//
//  Created by 刘伟 on 2017/1/11.
//  Copyright © 2017年 江苏十分便民. All rights reserved.
//

#import "FatherModel.h"
#import "CarInfoModel.h"
@interface ParagramConfigModel : FatherModel
@property(nonatomic,strong)CarInfoModel*car_info;
@property(nonatomic,strong)CarInfoModel*confs;


//"24969": {
//        "confs": {
//        "conf_air": {
//            "CAR_ID": "24969",
//            "AIR_CON_MODEL": "自动●",
//            "REAR_AIR_CON": "●",
//            "REAR_OUTLET": "●",
//            "TEM_PAR_CON": "●",
//            "AIR_PUR": "●",
//            "ICE_BOX": "-"
//        },
//        "conf_basic": {
//            "CAR_ID": "24969",
//            "FACTORY_NAME": "一汽-大众奥迪",
//            "CAR_MODEL": "中大型车",
//            "ENGINE": "1.8T 190马力 L4",
//            "GEARBOX": "7挡双离合",
//            "LWH": "5036*1874*1466",
//            "BODY_STRUCTURE": "4门5座三厢车",
//            "CREATOR_ID": "-",
//            "MAX_SPEED": "235",
//            "HK_ACC_FA": "8.5",
//            "HK_ACC_ME": "-",
//            "HK_BRA_ME": "-",
//            "HK_CON_ME": "-",
//            "HK_CON_GOV": "6.5",
//            "GROUND_CL_ME": "-",
//            "VEHICLE_WARRANTY": "三年或10万公里",
//            "PRICE": "46.12"
//        },
//        "conf_body": {
//            "CAR_ID": "24969",
//            "CD": "5036",
//            "KD": "1874",
//            "GD": "1466",
//            "ZJ": "3012",
//            "QLJ": "-",
//            "HLJ": "-",
//            "LDJX": "110",
//            "ZBZL": "1750",
//            "CSJG": "三厢车",
//            "CMS": "4",
//            "ZWS": "5",
//            "YXRJ": "75",
//            "XLXRJ": "470"
//        },
//        "conf_brake": {
//            "CAR_ID": "24969",
//            "FRONT_BRAKE_TYPE": "通风盘式",
//            "REAR_BRAKE_TYPE": "通风盘式",
//            "PARK_BRAKE_TYPE": "电子驻车",
//            "FRONT_TIRE_TYPE": "245/45 R18 ",
//            "REAR_TIRE_TYPE": "245/45 R18 ",
//            "SPARE_TIRE_TYPE": "非全尺寸"
//        },
//        "conf_chassis": {
//            "CAR_ID": "24969",
//            "DRIVING_MODE": "前置前驱",
//            "FRONT_SU_TYPE": "五连杆式独立悬架",
//            "REAR_SU_TYPE": "梯形连杆式独立悬架",
//            "HELP_POWER_TYPE": "电动助力",
//            "BODY_STRUCTURE": "承载式",
//            "FOUR_DRIVE_TYPE": "-",
//            "DIFFERENTIAL": "-"
//        },
//        "conf_color": {
//            "car_id": "24969",
//            "name": "达科塔灰",
//            "value": "#64544E",
//            "type": "0"
//        },
//        "conf_elec": {
//            "CAR_ID": "-",
//            "ELEC_SUM_POWER": "-",
//            "ELEC_SUM_TOR": "-",
//            "ELEC_FR_POWER": "-",
//            "ELEC_FR_TOR": "-",
//            "ELEC_BE_POWER": "-",
//            "ELEC_BE_TOR": "-",
//            "ELEC_BATTERY_LIFE": "-",
//            "ELEC_BATTERY_CAP": "-",
//            "batteries_qa": "-",
//            "charge_time": "-",
//            "charging_pile_price": "-"
//        },
//        "conf_engine": {
//            "CAR_ID": "24969",
//            "ENGINE_MODEL": "-",
//            "ENGINE_CAPACITY": "1798",
//            "ENGINE_CAPACITY_LITRE": "1.8",
//            "ENGINE_AI_FORM": "涡轮增压",
//            "CYLIBDER_ARRANGEMENT": "L",
//            "CYLIBDER_NUM": "4",
//            "CYLIBDER_PERVALVE_NUM": "4",
//            "COMPRESSION_RATIO": "-",
//            "ADMISSION_GEAR": "DOHC",
//            "BORE": "-",
//            "STROKE": "-",
//            "ENGINE_MAX_HP": "190",
//            "ENGINE_MAX_PO": "140",
//            "ENGINE_MAX_PS": "4200-6200",
//            "ENGINE_MAX_NJ": "320",
//            "ENGINE_MAX_NS": "1400-4100",
//            "ENGINE_SP_TE": "-",
//            "ENGINE_FUEL_TYPE": "汽油",
//            "ENGINE_GAS_GRADE": "97号(京95号)",
//            "ENGINE_SUPPLY_MODE": "混合喷射",
//            "CYLINDER_HEAD_MATERIAL": "铝",
//            "CYLINDER_BODY_MATERIAL": "铁",
//            "ENV_STA": "国V"
//        },
//        "conf_extend": {
//            "CAR_ID": "24969",
//            "name": "前后排座椅加热功能",
//            "describe": "包含：前排座椅加热、后排座椅加热",
//            "price": "6000",
//            "value": "○"
//        },
//        "conf_gearbox": {
//            "CAR_ID": "24969",
//            "SHORT_NAME": "7挡双离合",
//            "GEAR_NUM": "7",
//            "GEAR_BOX_TYPE": "双离合变速箱(DCT)"
//        },
//        "conf_glass": {
//            "CAR_ID": "24969",
//            "FONT_ELEC_WIN": "前●",
//            "REAR_ELEC_WIN": "后●",
//            "PREV_CLIP_WIN": "●",
//            "ANTI_UV": "●",
//            "RV_ELEC_ADJ": "●",
//            "RV_HEAT": "●",
//            "IN_ANTI_GLARE": "内●",
//            "OUT_ANTI_GLARE": "外○",
//            "RV_ELEC_FOLD": "●",
//            "RV_MEMORY": "○",
//            "REAR_MID_SS": "●",
//            "REAR_SIDE_SS": "●",
//            "REAR_PRI_WIN": "-",
//            "SUN_SH_PLA": "●",
//            "REAR_WIPER": "-",
//            "AUTO_WIPER": "●"
//        },
//        "conf_in": {
//            "CAR_ID": "24969",
//            "LEA_STEER": "●",
//            "ADJ_STEER": "上下+前后调节",
//            "ADJ_STEEL_ELEC": "○",
//            "MULT_STEEL": "●",
//            "SHIFT_STEEL": "●",
//            "HEAT_STEEL": "-",
//            "remember_steel": "-",
//            "CRUISE_CON": "●",
//            "FRONT_PARK_RAD": "前●",
//            "REAR_PARK_RAD": "后●",
//            "REV_VIDEO": "●",
//            "DRI_COM_DIS": "●",
//            "HUD": "○",
//            "led_dashboard": "-"
//        },
//        "conf_light": {
//            "CAR_ID": "24969",
//            "HID": null,
//            "LED": null,
//            "dipped_beams": "LED",
//            "high_beams": "LED",
//            "DAY_RUN": "●",
//            "auto_beams": "○",
//            "AUTO_HL": "●",
//            "STEER_AUX": "-",
//            "STEER_HL": "-",
//            "FRONT_FOG": "-",
//            "HL_ADJ": "●",
//            "HL_WASH": "●",
//            "AIR_LIGHT": "○"
//        },
//        "conf_media": {
//            "CAR_ID": "24969",
//            "GPS": "●",
//            "LOS": "-",
//            "CCSC": "●",
//            "BLCP": "●",
//            "CTV": "○",
//            "BSC": "-",
//            "POWER": "-",
//            "OMI": "AUX+SD卡插槽",
//            "CD": "●",
//            "MSYS": "单碟DVD(选装多碟DVD)",
//            "AUDIO_BRAND": "(选装BOSE)",
//            "AUDIO_NUM": "10-11喇叭(选装≥12喇叭)"
//        },
//        "conf_oper": {
//            "CAR_ID": "24969",
//            "ABS": "●",
//            "EBD": "●",
//            "BRAKE_ASSIST": "●",
//            "TRAC_CON": "●",
//            "STAB_CON": "●",
//            "HS_ASSIST_CON": "●",
//            "AUTO_PARK": "●",
//            "STEEP_DROP": "-",
//            "VARI_SUSPEN": "(选装软硬+高低调节)",
//            "AIR_SUSPEN": "○",
//            "VARI_STEER_RATIO": "-",
//            "FRONT_AXLE_LIMIT": "-",
//            "MID_AXLE_LIMIT": "-",
//            "REAR_AXLE_LIMIT": "-"
//        },
//        "conf_outside": {
//            "CAR_ID": "24969",
//            "ELEC_SKY": "●",
//            "PAN_SKY": "○",
//            "SPORT_APP": "-",
//            "ALUM_WHEEL": "●",
//            "ELEC_DOOR_PULL": "-",
//            "SLID_DOOR": "-",
//            "ELEC_BACKUP": "○",
//            "SENSE_BACKUP": "-",
//            "roof_rack": "-"
//        },
//        "conf_safe": {
//            "CAR_ID": "24969",
//            "MAIN_DRIVER_AIRBAG": "主●",
//            "CO_DRIVER_AIRBAG": "副●",
//            "FRONT_SIDE_AIRBAG": "前●",
//            "REAR_SIDE_AIRBAG": "前●",
//            "FRONT_HEAD_AIRBAG": "前●",
//            "REAR_HEAD_AIRBAG": "前●",
//            "KNEE_AIRBAG": "-",
//            "TPMS": "●",
//            "RSC": "-",
//            "NO_SEATBELT_WARN": "●",
//            "ISOFIX": "●",
//            "ENGINE_ELEC_SEC": "●",
//            "CAR_LOCK": "●",
//            "REMOTE_KEY": "●",
//            "NOKEY_START": "●",
//            "NOKEY_ENTRY": "○"
//        },
//        "conf_seat": {
//            "CAR_ID": "24969",
//            "LEA": "真皮",
//            "SPORT": "-",
//            "HEI_ADJ": "●",
//            "LUM_ADJ": "○",
//            "SHO_ADJ": "-",
//            "MAIN_ELEC_ADJ": "主●",
//            "AUX_ELEC_ADJ": "副●",
//            "SEC_BACK_ANG_ADJ": "-",
//            "SEC_MOV_ADJ": "-",
//            "REAR_ELEC_ADJ": "-",
//            "ELEC_MEMORY": "○",
//            "FRONT_HEAT": "前○",
//            "REAR_HEAT": "后○",
//            "FRONT_VENT": "前○",
//            "REAR_VENT": "后○",
//            "FRONT_MASS": "前-",
//            "REAR_MASS": "后○",
//            "THIRD_ROW": "-",
//            "REAR_REC_WAY": "-",
//            "FRONT_CENT_RAIL": "前●",
//            "REAR_CENT_RAIL": "后●",
//            "REAR_RACK": "●"
//        },
//        "conf_tech": {
//            "CAR_ID": "24969",
//            "AUTO_PARK": "○",
//            "ENGINE_SS": "●",
//            "AUXILIARY": "○",
//            "LANE_DEP_WARN": "○",
//            "ACTIVE_SAFE": "-",
//            "ACTIVE_STEER": "-",
//            "NIGHT_VISION": "○",
//            "SPL_LCD": "-",
//            "ADA_CRU": "○",
//            "PAN_CAMERA": "●",
//            "OUT_COLOR": null,
//            "IN_COLOR": null
//        }
//    }
//},
//"25014": {
//    "car_info": {
//        "car_id": "25014",
//        "car_name": "2016款 TFSI 技术型",
//        "factory_price": "41.53",
//        "sale_state": "0",
//        "min_price": "35.30",
//        "max_price": "41.53"
//    },
//    "confs": {
//        "conf_air": {
//            "CAR_ID": "25014",
//            "AIR_CON_MODEL": "自动●",
//            "REAR_AIR_CON": "○",
//            "REAR_OUTLET": "●",
//            "TEM_PAR_CON": "●",
//            "AIR_PUR": "○",
//            "ICE_BOX": "-"
//        },
//        "conf_basic": {
//            "CAR_ID": "25014",
//            "FACTORY_NAME": "一汽-大众奥迪",
//            "CAR_MODEL": "中大型车",
//            "ENGINE": "1.8T 190马力 L4",
//            "GEARBOX": "7挡双离合",
//            "LWH": "5036*1874*1466",
//            "BODY_STRUCTURE": "4门5座三厢车",
//            "CREATOR_ID": "-",
//            "MAX_SPEED": "235",
//            "HK_ACC_FA": "8.5",
//            "HK_ACC_ME": "-",
//            "HK_BRA_ME": "-",
//            "HK_CON_ME": "-",
//            "HK_CON_GOV": "6.5",
//            "GROUND_CL_ME": "-",
//            "VEHICLE_WARRANTY": "三年或10万公里",
//            "PRICE": "41.53"
//        },
//        "conf_body": {
//            "CAR_ID": "25014",
//            "CD": "5036",
//            "KD": "1874",
//            "GD": "1466",
//            "ZJ": "3012",
//            "QLJ": "-",
//            "HLJ": "-",
//            "LDJX": "110",
//            "ZBZL": "1750",
//            "CSJG": "三厢车",
//            "CMS": "4",
//            "ZWS": "5",
//            "YXRJ": "75",
//            "XLXRJ": "470"
//        },
//        "conf_brake": {
//            "CAR_ID": "25014",
//            "FRONT_BRAKE_TYPE": "通风盘式",
//            "REAR_BRAKE_TYPE": "通风盘式",
//            "PARK_BRAKE_TYPE": "电子驻车",
//            "FRONT_TIRE_TYPE": "225/55 R17 ",
//            "REAR_TIRE_TYPE": "225/55 R17",
//            "SPARE_TIRE_TYPE": "非全尺寸"
//        },
//        "conf_chassis": {
//            "CAR_ID": "25014",
//            "DRIVING_MODE": "前置前驱",
//            "FRONT_SU_TYPE": "五连杆式独立悬架",
//            "REAR_SU_TYPE": "梯形连杆式独立悬架",
//            "HELP_POWER_TYPE": "电动助力",
//            "BODY_STRUCTURE": "承载式",
//            "FOUR_DRIVE_TYPE": "-",
//            "DIFFERENTIAL": "-"
//        },
//        "conf_color": {
//            "car_id": "25014",
//            "name": "摩尔棕/天鹅绒米色",
//            "value": "[#5E574D,#AD9B89]",
//            "type": "1"
//        },
//        "conf_elec": {
//            "CAR_ID": "-",
//            "ELEC_SUM_POWER": "-",
//            "ELEC_SUM_TOR": "-",
//            "ELEC_FR_POWER": "-",
//            "ELEC_FR_TOR": "-",
//            "ELEC_BE_POWER": "-",
//            "ELEC_BE_TOR": "-",
//            "ELEC_BATTERY_LIFE": "-",
//            "ELEC_BATTERY_CAP": "-",
//            "batteries_qa": "-",
//            "charge_time": "-",
//            "charging_pile_price": "-"
//        },
//        "conf_engine": {
//            "CAR_ID": "25014",
//            "ENGINE_MODEL": "-",
//            "ENGINE_CAPACITY": "1798",
//            "ENGINE_CAPACITY_LITRE": "1.8",
//            "ENGINE_AI_FORM": "涡轮增压",
//            "CYLIBDER_ARRANGEMENT": "L",
//            "CYLIBDER_NUM": "4",
//            "CYLIBDER_PERVALVE_NUM": "4",
//            "COMPRESSION_RATIO": "-",
//            "ADMISSION_GEAR": "DOHC",
//            "BORE": "-",
//            "STROKE": "-",
//            "ENGINE_MAX_HP": "190",
//            "ENGINE_MAX_PO": "140",
//            "ENGINE_MAX_PS": "4200-6200",
//            "ENGINE_MAX_NJ": "320",
//            "ENGINE_MAX_NS": "1400-4100",
//            "ENGINE_SP_TE": "-",
//            "ENGINE_FUEL_TYPE": "汽油",
//            "ENGINE_GAS_GRADE": "97号(京95号)",
//            "ENGINE_SUPPLY_MODE": "混合喷射",
//            "CYLINDER_HEAD_MATERIAL": "铝",
//            "CYLINDER_BODY_MATERIAL": "铁",
//            "ENV_STA": "国V"
//        },
//        "conf_extend": {
//            "CAR_ID": "25014",
//            "name": "外后视镜记忆和自动防眩目",
//            "describe": "包含：后视镜记忆功能、外后视镜自动防眩目功能。",
//            "price": "2500",
//            "value": "○"
//        },
//        "conf_gearbox": {
//            "CAR_ID": "25014",
//            "SHORT_NAME": "7挡双离合",
//            "GEAR_NUM": "7",
//            "GEAR_BOX_TYPE": "双离合变速箱(DCT)"
//        },
//        "conf_glass": {
//            "CAR_ID": "25014",
//            "FONT_ELEC_WIN": "前●",
//            "REAR_ELEC_WIN": "后●",
//            "PREV_CLIP_WIN": "●",
//            "ANTI_UV": "●",
//            "RV_ELEC_ADJ": "●",
//            "RV_HEAT": "●",
//            "IN_ANTI_GLARE": "内●",
//            "OUT_ANTI_GLARE": "外○",
//            "RV_ELEC_FOLD": "●",
//            "RV_MEMORY": "○",
//            "REAR_MID_SS": "●",
//            "REAR_SIDE_SS": "●",
//            "REAR_PRI_WIN": "-",
//            "SUN_SH_PLA": "●",
//            "REAR_WIPER": "-",
//            "AUTO_WIPER": "●"
//        },
//        "conf_in": {
//            "CAR_ID": "25014",
//            "LEA_STEER": "●",
//            "ADJ_STEER": "上下+前后调节",
//            "ADJ_STEEL_ELEC": "○",
//            "MULT_STEEL": "●",
//            "SHIFT_STEEL": "●",
//            "HEAT_STEEL": "-",
//            "remember_steel": "-",
//            "CRUISE_CON": "●",
//            "FRONT_PARK_RAD": "前●",
//            "REAR_PARK_RAD": "后●",
//            "REV_VIDEO": "●",
//            "DRI_COM_DIS": "●",
//            "HUD": "○",
//            "led_dashboard": "-"
//        },
//        "conf_light": {
//            "CAR_ID": "25014",
//            "HID": null,
//            "LED": null,
//            "dipped_beams": "氙气(选装LED)",
//            "high_beams": "氙气(选装LED)",
//            "DAY_RUN": "●",
//            "auto_beams": "○",
//            "AUTO_HL": "●",
//            "STEER_AUX": "-",
//            "STEER_HL": "-",
//            "FRONT_FOG": "-",
//            "HL_ADJ": "●",
//            "HL_WASH": "●",
//            "AIR_LIGHT": "○"
//        },
//        "conf_media": {
//            "CAR_ID": "25014",
//            "GPS": "●",
//            "LOS": "-",
//            "CCSC": "●",
//            "BLCP": "●",
//            "CTV": "○",
//            "BSC": "-",
//            "POWER": "-",
//            "OMI": "AUX+SD卡插槽",
//            "CD": "●",
//            "MSYS": "单碟DVD(选装多碟DVD)",
//            "AUDIO_BRAND": "(选装BOSE)",
//            "AUDIO_NUM": "10-11喇叭(选装≥12喇叭)"
//        },
//        "conf_oper": {
//            "CAR_ID": "25014",
//            "ABS": "●",
//            "EBD": "●",
//            "BRAKE_ASSIST": "●",
//            "TRAC_CON": "●",
//            "STAB_CON": "●",
//            "HS_ASSIST_CON": "●",
//            "AUTO_PARK": "●",
//            "STEEP_DROP": "-",
//            "VARI_SUSPEN": "(选装软硬+高低调节)",
//            "AIR_SUSPEN": "○",
//            "VARI_STEER_RATIO": "-",
//            "FRONT_AXLE_LIMIT": "-",
//            "MID_AXLE_LIMIT": "-",
//            "REAR_AXLE_LIMIT": "-"
//        },
//        "conf_outside": {
//            "CAR_ID": "25014",
//            "ELEC_SKY": "●",
//            "PAN_SKY": "○",
//            "SPORT_APP": "-",
//            "ALUM_WHEEL": "●",
//            "ELEC_DOOR_PULL": "-",
//            "SLID_DOOR": "-",
//            "ELEC_BACKUP": "○",
//            "SENSE_BACKUP": "-",
//            "roof_rack": "-"
//        },
//        "conf_safe": {
//            "CAR_ID": "25014",
//            "MAIN_DRIVER_AIRBAG": "主●",
//            "CO_DRIVER_AIRBAG": "副●",
//            "FRONT_SIDE_AIRBAG": "前●",
//            "REAR_SIDE_AIRBAG": "前●",
//            "FRONT_HEAD_AIRBAG": "前●",
//            "REAR_HEAD_AIRBAG": "前●",
//            "KNEE_AIRBAG": "-",
//            "TPMS": "●",
//            "RSC": "-",
//            "NO_SEATBELT_WARN": "●",
//            "ISOFIX": "●",
//            "ENGINE_ELEC_SEC": "●",
//            "CAR_LOCK": "●",
//            "REMOTE_KEY": "●",
//            "NOKEY_START": "●",
//            "NOKEY_ENTRY": "○"
//        },
//        "conf_seat": {
//            "CAR_ID": "25014",
//            "LEA": "织物(选装真皮)",
//            "SPORT": "-",
//            "HEI_ADJ": "●",
//            "LUM_ADJ": "○",
//            "SHO_ADJ": "-",
//            "MAIN_ELEC_ADJ": "主●",
//            "AUX_ELEC_ADJ": "副●",
//            "SEC_BACK_ANG_ADJ": "-",
//            "SEC_MOV_ADJ": "-",
//            "REAR_ELEC_ADJ": "-",
//            "ELEC_MEMORY": "○",
//            "FRONT_HEAT": "前○",
//            "REAR_HEAT": "后○",
//            "FRONT_VENT": "前○",
//            "REAR_VENT": "后○",
//            "FRONT_MASS": "前-",
//            "REAR_MASS": "后○",
//            "THIRD_ROW": "-",
//            "REAR_REC_WAY": "-",
//            "FRONT_CENT_RAIL": "前●",
//            "REAR_CENT_RAIL": "后●",
//            "REAR_RACK": "●"
//        },
//        "conf_tech": {
//            "CAR_ID": "25014",
//            "AUTO_PARK": "○",
//            "ENGINE_SS": "●",
//            "AUXILIARY": "○",
//            "LANE_DEP_WARN": "○",
//            "ACTIVE_SAFE": "-",
//            "ACTIVE_STEER": "-",
//            "NIGHT_VISION": "○",
//            "SPL_LCD": "-",
//            "ADA_CRU": "○",
//            "PAN_CAMERA": "○",
//            "OUT_COLOR": null,
//            "IN_COLOR": null
//        }
//    }
//},

@end
